<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="N-20S5PF2GG0F1" name="com.inetBanking.testCases.TC_TodoAddItem_001" tests="13" failures="1" timestamp="02 Sep 2022 03:59:52 GMT" time="4.405" errors="0">
  <testcase name="testNavigateToTodosPage" time="1.155" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.235" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.219" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.206" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="1.344" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.181" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.191" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.223" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItem" time="0.201" classname="com.inetBanking.testCases.TC_TodoAddItem_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.inetBanking.testCases.TC_TodoAddItem_001.addItem(TC_TodoAddItem_001.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- addItem -->
  <testcase name="addItemBeginswithSpaces" time="0.227" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="addItemBeginswithSpaces" time="0.223" classname="com.inetBanking.testCases.TC_TodoAddItem_001"/>
  <testcase name="checkFootercount" time="0.000" classname="com.inetBanking.testCases.TC_TodoAddItem_001">
    <skipped/>
  </testcase> <!-- checkFootercount -->
  <testcase name="addItemwithNullorEmpty" classname="com.inetBanking.testCases.TC_TodoAddItem_001">
    <skipped/>
  </testcase> <!-- addItemwithNullorEmpty -->
</testsuite> <!-- com.inetBanking.testCases.TC_TodoAddItem_001 -->
